spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deltadrive
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
      hibernate.spatial.enabled: true



token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
